version: "3.9"
services:

  bot:
    build: .
    restart: always
    command: sh -c "python3 main.py"
    env_file:
      - ./.env
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    restart: always
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    restart: always
    env_file:
      - ./.env